### ISSUE TITLE
Compatibility with Edge

### ISSUE THREAD

**Issue by edum18** [mattrothenberg/vue-flip-toolkit#12]
Hey,
This doesn't seem to work on Edge.
It gives me this error:

![image](https://user-images.githubusercontent.com/7084077/64852571-86734480-d611-11e9-874c-728305187fd9.png)

![image](https://user-images.githubusercontent.com/7084077/64852495-680d4900-d611-11e9-9cb9-96742129fda0.png)

**Comment by mattrothenberg** [comment]
Hi @edum18, can you provide a little more context on your project? Perhaps a link to a GitHub repo?

Are you using Babel to transpile your JS into a format that the browser can parse?

**Comment by mattrothenberg** [comment]
@edum18 In the meantime, I cut a new beta release of the library where the dist files are transpiled by babel – `1.14.1-beta-1`.

Try this CodeSandbox in Edge, or adjust your project so that it pulls in the beta version of the library and let me know how it works out.
https://codesandbox.io/s/vue-template-t6n3k?fontsize=14

**Comment by mattrothenberg** [comment]
Ping @edum18 . Closing the issue by end of day if I don't hear back from ya!

**Comment by edum18** [comment]
> Ping @edum18 . Closing the issue by end of day if I don't hear back from ya!

Hey, with that new version now it works on Edge, thanks :)

**Comment by mattrothenberg** [comment]
Thanks @edum18 .

Just published [1.5.0](https://www.npmjs.com/package/vue-flip-toolkit).
